#!/bin/sh

# Online documentation update pre-push hook

remote="$1"
url="$2"

docs_repo="git@github.com:JPenuchot/ctbench-docs.git"
docs_out_dir="/tmp/ctbench-docs"

srcdir=$(pwd)

branch=$(git rev-parse --abbrev-ref HEAD)

echo Current branch: $branch

if [[ "$branch" != "main" ]]; then
	echo "Branch is not main, exiting."
	exit 0
fi

echo "Updating docs..."

rm -rf $docs_out_dir
mkdir -p $docs_out_dir

echo "- Building docs..."

cmake -S . -B build \
	-DCMAKE_BUILD_TYPE:STRING=Release \
	-DCTBENCH_ENABLE_DOCS:BOOL=TRUE \
	-DCTBENCH_ENABLE_TESTS:BOOL=FALSE \
	-DDOXYGEN_HTML_OUTPUT:PATH=$docs_out_dir
cmake --build build --target docs

rm -rf build-docs

cd $docs_out_dir

echo "- Updating target repo"

git init
git add .
git commit -m "docs"
git remote add gh $docs_repo
git push -u gh main --force
