#!/bin/sh

# Online documentation update pre-push hook

remote="$1"
url="$2"

docs_repo="git@github.com:JPenuchot/ctbench-docs.git"
docs_out_dir="/tmp/ctbench-docs"

srcdir=$(pwd)

branch=$(git rev-parse --abbrev-ref HEAD)

if [[ $branch -ne "main" ]]; then
	exit 0
fi

echo "Updating docs..."

rm -rf $docs_out_dir
mkdir -p $docs_out_dir

mkdir build-docs
cd build-docs

echo "- Building docs..."

CXX=clang++ CC=clang cmake ../ -G Ninja \
	-DCMAKE_BUILD_TYPE:STRING=Release \
	-DENABLE_DOCS:BOOL=TRUE \
	-DDOXYGEN_HTML_OUTPUT:PATH=$docs_out_dir
ninja docs

cd ../
rm -rf build-docs

cd $docs_out_dir

echo "- Updating target repo"

git init
git add .
git commit -m "docs"
git remote add gh $docs_repo
git push -u gh main --force
