name: ctbench testing
on: [push]

jobs:
  archlinux-testing:
    runs-on: self-hosted
    container:
      image: archlinux/archlinux
      options: -u root
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Compiling and running ctbench tests on Archlinux
        uses: ./.github/actions/run-tests-archlinux
      - uses: actions/upload-artifact@v3
        with:
          name: build_result
          path: build/

  ubuntu-testing:
    runs-on: self-hosted
    container:
      image: ubuntu:23.04
      options: -u root
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Compiling and running ctbench tests on Ubuntu
        uses: ./.github/actions/run-tests-ubuntu
      - uses: actions/upload-artifact@v3
        with:
          name: build_result
          path: build/
