name: ctbench tests
on: [push]

jobs:
  clang:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Compiling and running ctbench tests
        uses: ./.github/actions/run-tests
